name: peterhorton
favicon: null
layout_spectrum: 0.40187761443667114
typography_spectrum: 0.9200079862494022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.677545512560755
  lightness: 0.22737690131179988
  saturation: 0.6894250828772783
  rhythmicContrast: 0.352168952813372
purpose: []
